---
# A script that runs a Gradle Docker image to run integration tests
resources:
- name: cf-spring-trader-repo
  type: git
  source:
    #uri: https://github.com/cf-platform-eng/springtrader-cf
    uri: https://github.com/pivotal-anz/cf-SpringBootTrader
    branch: master
- name: ci-ultimate-repo
  type: git
  source:
    uri: https://github.com/pivotal-anz/ci-ultimate
    branch: master
- name: pcf-bedazzle
  type: cf
  source:
    api: https://api.pcfdemo.info
    username: ci@pcf-demo.com
    password: demo
    organization: Bedazzle
    space: development
    skip_cert_check: true

jobs:
- name: ci-pipeline
  plan:
  - get: ci-ultimate-repo
    trigger: true
  - get: cf-spring-trader-repo
    trigger: true
  # Unit test failing on our Concourse on AWS instance 
  - task: unit
    file: ci-ultimate-repo/ci/ci-task.yml
  # Now push each app to Cloud Foundry, one at a time (sigh)
  - put: pcf-bedazzle
    params:
      manifest: cf-spring-trader-repo/manifest-registry-ci.yml
      path: unit/cf-spring-trader-repo/registryServer/build/libs/registry-0.2.jar
  - put: pcf-bedazzle
    params:
      manifest: cf-spring-trader-repo/manifest-quotes.yml
      path: unit/cf-spring-trader-repo/springboottrades-quotes/build/libs/quotes-0.2.jar
