---
# A script that runs a maven Docker image
resources:
- name: cf-spring-trader-repo
  type: git
  source:
    uri: https://github.com/cf-platform-eng/springtrader-cf
    branch: master

- name: ci-ultimate-repo
  type: git
  source:
    uri: https://github.com/pivotal-anz/ci-ultimate
    branch: master

jobs:
- name: ci-pipeline
  plan:
  - get: cf-spring-trader-repo
    trigger: true
  - get: ci-ultimate-repo
    trigger: true
  - task: unit
    file: ci-ultimate/ci/ci-task.yml
