---
# A script that runs a Gradle Docker image to run integration tests
resources:
- name: cf-spring-trader-repo
  type: git
  source:
    uri: https://github.com/cf-platform-eng/springtrader-cf
    branch: master
- name: ci-ultimate-repo
  type: git
  source:
    uri: https://github.com/pivotal-anz/ci-ultimate
    branch: master

jobs:
- name: ci-pipeline
  plan:
  - get: ci-ultimate-repo
    trigger: true
#  - get: cf-spring-trader-repo
#    trigger: true
  - task: unit
    file: ci-ultimate-repo/ci/ci-task.yml
