#!/bin/sh
export TERM=xterm

echo "Running checks"
java -version
unzip -q ci-ultimate-repo/tools/gradle-2.6-bin.zip
gradle-2.6/bin/gradle -version

echo "Running tests"
cd cf-spring-trader-repo
pwd
# Test failing on Concourse on AWS, just do an assemble for deployment to PCF
../gradle-2.6/bin/gradle -x test assemble

