#!/bin/sh
echo "Running checks"
ls -l /usr/bin/java
echo "---"
java -version
echo "---"
echo $PATH
echo "---"
ls /
echo "---"
ls -l /usr/local/bundle/bin
echo "---"
pwd
echo "---"
ls
echo "---"
ci-ultimate-repo/tools/gradle/bin/gradle -version
