#!/bin/sh
export TERM=xterm

echo "Running checks"
java -version
unzip -q ci-ultimate-repo/tools/gradle-2.6-bin.zip
gradle-2.6/bin/gradle -version

echo "Running tests"
cd cf-spring-trader-repo
pwd

# If test fails on Concourse on AWS, just do an assemble for deployment to PCF, use -x
../gradle-2.6/bin/gradle test assemble

